require("scripts.signals.ram")
require("scripts.signals.bat")
require("scripts.signals.cpu")
require("scripts.signals.bright")
require("scripts.signals.vol")
require("scripts.signals.disk")
require("scripts.signals.wifi")
require("scripts.signals.weather")
