[window]
padding = { x = 20, y = 20 }
decorations = "None"

[font]
normal = { family = "Iosevka Nerd font", style = "Regular" }
bold = { family = "Iosevka Nerd font", style = "Regular" }
size = 16

[colors.primary]
background = '#1D1D20'
foreground = '#ffffff'

[colors.normal]
black      = '#28282C'
red        = '#c01c28'
green      = '#26a269'
yellow     = '#a2734c'
blue       = '#12488b'
magenta    = '#a347ba'
cyan       = '#2aa1b3'
white      = '#d0cfcc'

[colors.bright]
black      = '#5e5c64'
red        = '#f66151'
green      = '#33d17a'
yellow     = '#e9ad0c'
blue       = '#2a7bde'
magenta    = '#c061cb'
cyan       = '#33c7de'
white      = '#ffffff'

[cursor.style]
shape = "Beam"
